### ISSUE TITLE
Possible to convert a Reader to a Builder

### ISSUE THREAD

**Issue by FallingSnow** [capnproto/capnproto-rust#106]
I'm using capnproto's format to store data on disk. Sometimes I want to read and modify that data and write it back to disk. Unfortunately reading the data of disk only produces a reader that doesn't seem to be able to be modified.

Is there a way to get around this other than rewriting all the data from the reader to a builder and then modifying what you want?

**Comment by dwrensha** [comment]
That's right. In order to modify the data, you'll need to copy it into a `Builder`. Probably the best way to do that is with `message::Builder::set_root()`, which should be pretty cheap.

In theory we could allow in-place modification, but it would involve some nontrivial engineering.

**Comment by FallingSnow** [comment]
I'm using it in a database where performance is important to me so the cheapest option would be desirable, even if it took some extra work. I'll try `message::Builder::set_root()` and see what the performance cost is like.

Thank you for taking the time to respond.

**Comment by FallingSnow** [comment]
Sorry but I'm just trying to get a deeper understanding of capnproto-rust. Why is there a discrimination between Reader and Builder? Was this a necessity to using capnproto on rust or was this more of a design choice?

**Comment by dwrensha** [comment]
There's a lot of logic that differs between the two cases.


Suppose we have
```capnp
struct Foo {
   a @0 :UInt32;
}

struct Bar {
   b @0 :Foo;
}
```

If `bar_reader: bar::Reader`, and we call `bar_reader.get_b()`, it's actually possible that there is not even a pointer allocated for `b` (perhaps the message was written with an [earlier version of the schema](https://capnproto.org/language.html#evolving-your-protocol)). So capnproto-rust needs to check whether a pointer for the `b` field exists. If it doesn't exist, (or if it does exist and is null) capnproto-rust returns a default `foo::Reader`. If it does exist, capnproto-rust needs to check whether it points in bounds. If not, then we an error. If so, then we get a `foo::Reader` that points to it.

Compare this to the case where we have `bar_builder: bar::Builder` and we call `bar_builder.get_b()`. In this case, since we've constructed the message ourselves, we can be sure that there is a pointer allocated for the `b` field. Moreover, if that pointer is non-null, we know that it points in bounds, because we've constructed this message ourselves. If the pointer is null, `get_b()` allocates new space for the `Foo` struct body, and returns a new `foo::Builder` pointing to it. Even if the pointer exists and points to already-allocated memory, it may point to a `Foo` constructed with an old version, so we may need to reallocate.

Note that capnproto-c++ and capnproto-java also work in terms of Readers and Builders that have very similar properties to capnproto-rust's.

**Comment by FallingSnow** [comment]
Thanks for taking the time to provide an explanation.

So it seems like builder is an optimization of reader that doesn't need to do certain checks that reader does?

But why do a "deep copy" of the reader's data rather than consuming the source when using `message::Builder::set_root()`? That way the user can decide when they want to keep the reader by using a `.clone()`.
