### ISSUE TITLE
Add a syntax extension

### ISSUE THREAD

**Issue by emberian** [capnproto/capnproto-rust#11]
Especially with cargo, generating code using tools can be annoying. Add a syntax extension that will generate the code into a module. With `include_str` etc, no flexibility is lost.

**Comment by tv42** [comment]
Can this ancient bug be closed? It seems using a `build.rs` build script and `include!` of files from `OUT_DIR` is the standard way to do code generation for Rust these days, and `capnpc` makes that as easy as it's anywhere.

(I do wish we didn't need the C++ binary, but that's not what this issue is about.)

**Comment by dwrensha** [comment]
This issue was opened in September of 2014. In November of 2014, capnproto-rust started using a `build.rs` build script, which I guess must have been a newly introduced feature of Cargo around then: https://github.com/capnproto/capnp-rpc-rust/commit/33ac799c31d4e3949ae209a75d7f3d10914c4f0b

I could still imagine someone wanting to use a procedural macro, like `capnp_mod!(example.capnp)` to avoid needing an explicit build script, but it's unclear whether that's what this issue is exactly asking about. If someone wants that, they can open a new issue (but be advised that I prefer to avoid proc-macro).
