### ISSUE TITLE
Tokio main sample

### ISSUE THREAD

**Issue by bfrog** [capnproto/capnproto-rust#158]
The samples seem to mostly use async-std, I have no strong feelings about tokio and async-std, but most of the other libraries I'd like to use (hyper, reqwest, trust-dns, etc) mostly use the tokio AsyncRead/AsyncWrite, and tokio::main macro.

It would be nice to see capnproto support these without the need of the external unpublished adapter crate.

**Comment by dwrensha** [comment]
> It would be nice to see capnproto support these without the need of the external unpublished adapter crate.

Yeah, I agree. I had been under the impression that there would be some kind of official `futures::AsyncRead` <-> `tokio::AsyncRead` adapter module, but it seems like that hasn't happened yet.

I suppose we could include our own adapters, perhaps as an optional feature in the `capnp-futures` crate.

Longer term, I think we might want the `capnp-rpc` defined in terms of streams and sinks of messages, rather than I/O objects.

**Comment by kwohlfahrt** [comment]
There is now an official adapter, as of tokio-rs/tokio#2117. It isn't released as a crate yet, but it works if you use a git dependency.

**Comment by dwrensha** [comment]
Thanks for the tip @kwohlfahrt. I've switched to `tokio_util` in 4e6859c74251897a44c222e9679eea74145f2e33

**Comment by dwrensha** [comment]
In 6fa77f018215a50674b343e6a5ea082b6d7bbe67 I updated the http-requests example to use `tokio::main`.

In 3e77df78d341b46ebe2ea74467ca40244c4056ac I switched the calculator example to `tokio`, including usage of `tokio::main`.
