### ISSUE TITLE
Cannot infer types

### ISSUE THREAD

**Issue by b00f** [capnproto/capnproto-rust#177]
Sometimes for Inferring types it is needed to manually add types to variables. Is there any way to mitigate this?

**Comment by dwrensha** [comment]
Can you provide an example?

**Comment by b00f** [comment]
As an example: `capnp_rpc::new_client(...)`. I know you have some restriction because of generic types.

**Comment by dwrensha** [comment]
You need to provide the `Client` type for `new_client` because it's possible that a single type might implement multiple `Server` traits. Note that if there are generics, you can sometimes get away with leaving them implicit using an underscore, like here:
https://github.com/capnproto/capnproto-rust/blob/23ee18c5844cd4ab39dfb8aea05f757cad79d609/capnp-rpc/examples/pubsub/server.rs#L122

**Comment by b00f** [comment]
I really understand the reason. My point is if there is a way to avoid generic (?) in development phase, consider it. I can see this error other parts. 
A always believe a library should "provides more, request less".

**Comment by dwrensha** [comment]
I'm sorry, I don't understand what you are saying. It sounds like you might be referring to the deprecation of the `ToClient` types in a57e7359817631eb6d4ffb97ae0ebccac753c9b8, but as I see it, that change was a big win, because now a lot less boilerplate code is needed.
