### ISSUE TITLE
error message diplays when i execute './configure --prefix=$HOME'

### ISSUE THREAD

**Issue by lamei1224** [capnproto/capnproto-rust#189]
![error](https://user-images.githubusercontent.com/55862430/85220523-ac1e4d00-b3de-11ea-8da3-8f709edfde95.png)

**Comment by dwrensha** [comment]
Looks like the relevant error message is "A compiler with support for C++14 error language features is required". See https://capnproto.org/install.html#supported-compilers

Instead of installing from source, you may also be able to get a packaged distribution of the `capnp` tool via `sudo apt-get capnproto` or similar.

**Comment by lamei1224** [comment]
yeah，i have solved this problem,thank you very much.
