### ISSUE TITLE
Remove need for `reborrow()`

### ISSUE THREAD

**Issue by jyn514** [capnproto/capnproto-rust#241]
I looked at the 2014 blog post, which says:

> The `Builder` types of [capnproto-rust](https://github.com/dwrensha/capnproto-rust) also need to
provide an exclusivity guarantee.  Recall that if `Foo` is a struct defined in a Cap'n Proto schema,
then a `foo::Builder<'a>` provides access to a writable location in arena-allocated memory that
contains a `Foo` in [Cap'n Proto format](https://kentonv.github.io/capnproto/encoding.html).  To
protect access to that memory, a `foo::Builder<'a>` ought to behave as if it were a `&'a mut Foo`,
even though the `Foo` type cannot directly exist in Rust (because Cap'n Proto struct layout differs
from Rust struct layout).

The solution it comes up with is to use `reborrow()` everywhere. But that's not necessary, since it can just take `&mut self` in the accessors instead of taking an owned value; that both enforces exclusive access and allows reusing the builder later without needing a reborrow() call.

**Comment by jyn514** [comment]
Note that this is a breaking change, since `let my_builder = Builder::new_default(); my_builder.init_x()` compiles if `init_x` takes `self`, but not if it takes `mut self` (the user has to update their code to use `let mut my_builder`).

**Comment by dwrensha** [comment]
The problem with taking `&mut self` is that then you can't write functions that return mutable references to the interior of a message. For example, suppose we have these types:

```capnp
struct Foo {
  blob @0 : Data;
}
struct Bar {
  foo0 @0 : Foo;
  foo1 @1 : Foo;
}
```

and suppose that I want to write a function that takes a mutable reference to a `Bar` and returns a mutable reference to a `Foo`.

With the current setup I can write a function like this:
```rust
fn return_foo_mut<'a>(get_foo0: bool, mut bar: Bar::Builder<'a>) -> capnp::Result<Foo::Builder<'a>> {
   if get_foo0 { bar.get_foo0() } else { bar.get_foo1() }
}
```

How would I write an equivalent function after making the changes that you are proposing?

**Comment by jyn514** [comment]
You'd change the function to take a mutable reference instead of an owned value:
```rust
fn return_foo_mut<'a>(get_foo0: bool, mut bar: &'a mut Bar::Builder<'_>) -> capnp::Result<Foo::Builder<'a>> {
   if get_foo0 { bar.get_foo0() } else { bar.get_foo1() }
}
```

**Comment by dwrensha** [comment]
Wow, it looks like that does work! I don't know how I managed to overlook this simpler solution for so long.

**Comment by dwrensha** [comment]
> ~Note that this is a breaking change, since `let my_builder = Builder::new_default(); my_builder.init_x()` compiles if `init_x` takes `self`, but not if it takes `mut self` (the user has to update their code to use `let mut my_builder`).~ No it's not, I confused myself - you can't write `init_x()` currently, you have to write `my_builder.reborrow().init_x()`, which will still compile after this change.

I think the changes in function signatures would be enough to merit a "major" version bump. I.e., if we landed these changes, I would want to bump from version 0.14 to 0.15. I also think that we would want to mark the `reborrow()` functions as deprecated, rather than deleting them.

**Comment by dwrensha** [comment]
Or maybe we'd keep the `reborrow()` functions around indefinitely? Maybe there's no strong reason to quickly deprecate them.

**Comment by jyn514** [comment]
Hmm, personally I would lean in favor of deprecating them so people see there's a simpler way to do the same thing. But I don't feel strongly, it's your crate :)

**Comment by dwrensha** [comment]
What about a function like this? I don't see how we can get this pass the borrow checker.
```rust
    fn return_inner_slice<'a>(bar : &'a mut bar::Builder<'a>) -> capnp::Result<&'a mut [u8]> {
        Ok(&mut bar.get_foo0()?.get_blob()?[5..10])
    }
```

```
error[E0515]: cannot return value referencing temporary value
   --> example/addressbook/addressbook.rs:121:9
    |
121 |         Ok(&mut bar.get_foo0()?.get_blob()?[5..10])
    |         ^^^^^^^^---------------^^^^^^^^^^^^^^^^^^^^
    |         |       |
    |         |       temporary value created here
    |         returns a value referencing data owned by the current function
```

**Comment by jyn514** [comment]
@dwrensha that compiles for me without changes. Are you sure you're using the right branch?

In general, I think you could eventually find *some* function that compiles currently but wouldn't compile with `&mut`, but I think having to rewrite that small bit is worth it to have semantics consistent with the rest of the language.

**Comment by dwrensha** [comment]
I'm using your branch, but with the `&'a mut self` change that mention here: https://github.com/capnproto/capnproto-rust/pull/242#discussion_r768316239

**Comment by jyn514** [comment]
> What about a function like this? I don't see how we can get this to pass the borrow checker.

Hmm, ok, I see the issue - `get_foo0()` returns a new value, so `get_blob()` can't return a reference that lasts longer than the new `Builder`.

The way I normally solve this is by returning a reference to an existing field, so the lifetime isn't shortened, so the new signature would be e.g. `fn get_foo0(&'a mut self) -> Result<&'a mut Builder<'a>>`. But I'm not sure how to make that work with autogenerated code ...

I think a better solution is instead of requiring `&'a mut self`, allow an arbitrary lifetime *but* only make the return `Builder` valid for that lifetime:

```rust
fn get_foo0<'s>(&'s mut self) -> Result<Builder<'s>>
```

That should prevent aliasing without preventing you from returning the borrow from a function.

**Comment by dwrensha** [comment]
As I understand things, I think your version will still get the `cannot return value referencing temporary value` error, because the reference taken by `get_blob()` is to a function-local temporary.

**Comment by dwrensha** [comment]
Closing, because I don't see a way to make this work.

The one avenue forward that seems potentially promising to me would be to add a `Reborrow` trait to core Rust and to have it automatically insert `reborrow()` calls when appropriate. This would give users a way to hook into the existing reborrow magic, which currently only works for built-in references.

**Comment by pfrommerd** [comment]
Instead of get_{}(), why not have an into_{}() function that consumes the Builder? (basically how get() methods work right now) With the earlier suggestion of using
```rust
fn get_foo0<'s>(&'s mut self) -> Result<Builder<'s>>
```
You would do
```rust
    fn return_inner_slice<'a>(bar : &'a mut bar::Builder<'a>) -> capnp::Result<&'a mut [u8]> {
        Ok(&mut bar.get_foo0()?.into_blob()?[5..10])
    }
```
Since get_foo0() returns a Result<Builder<'a>>, into_blob would consume that builder and can return the proper Result<&'a mut[u8]> without taking a reference to local temporary, since the returned reference only needs to outlive the underlying buffer, not the temporary object. Since you have shortened the lifetime of the returned object to the duration of the mutable borrow for the parent, this should also prevent aliasing. The into_{}() syntax would also be consistent with the rest of the rust ecosystem.

Am I missing something?

**Comment by dwrensha** [comment]
Interesting idea. Yes, we could make the `Builder::get_*()` and `Builder::init_*()` methods take a `&mut self` and we could add new methods `Builder::into_*()` and `Builder::init_into_*()` (not sure about the naming on the last one there). That would work.

Pros:
 - less boilerplate
 - more optimized for the common case

Cons:
 - more generated code
 - more things for users to learn about
 - breaking change
 - if Rust ever does get a `Reborrow` trait, then we will want to go back to how things are now

**Comment by pfrommerd** [comment]
The fact that it makes more generated code is probably the biggest drawback. I think the into_* and get_* syntax would be more intuitive for users since having get_* consume self is quite strange, while having into_* methods consume the object is standard rust.

The real fix here is I think not so much a Reborrow trait, but a more intelligent borrow checker where for `Builder<'s>`
```rust
fn get_foo0<'a>(&'a mut self) -> Result<Builder<'s>>
```
And you could enforce that 'a mut self is borrowed for the lifetime of the returned object, or until the 'a mut self is dropped (i.e the rest of its life), whichever is shorter. Essentially a pseudo borrow where &'a mut self needs to be borrowed while the returned object is alive, but it is fine for &'a mut self to be dropped since &'a mut self doesn't actually own the buffer. This would have to be transitive in that if the &'a mut self is in itself returned from a get_*, the mutable borrow for its parent would also need to be extended by the lifetime of the returned builder, even if the &'a mut self Builder is dropped. I think Rust's borrow checker just currently isn't set up to handle this scenario, but perhaps one day we will have a way of cleanly covering this case.

**Comment by dwrensha** [comment]
> having get_* consume self is quite strange

It doesn't seem overly strange to me. I think of a `Builder<'a>` as a simulation of a `&'a mut T`. Consider the following perspective: a method like `fn foo (&'a mut self)` actually does take the `&'a mut self` by value, but it's made convenient because the compiler automatically inserts an implicit "reborrow" if necessary. The signature of this implicit reborrow is something like `fn reborrow<'a, 'b>(&'a &'b mut T) -> &'a mut T`.

For `Builder<'a>` we need to explicitly add the `reborrow()` calls, until maybe someday rustc gains a feature that lets us hook into implicit reborrowing.

> And you could somehow enforce that 'a mut self is borrowed for the lifetime of the returned object, or until the 'a mut self is dropped (i.e the rest of its life), whichever is shorter

I think what you're describing here is equivalent to the semantics we would get with the `Reborrow` trait that I'm imagining.

Maybe the way forward here is for someone (me, I guess, when I have some time) to write up a Rust RFC about the `Reborrow` trait. (I know there has been at least some casual discussion about it previously, but I'm having trouble finding it.) If the broader community seems to think that rustc is unlikely to ever support such a thing, then I would be more receptive to the changes that you are suggesting.

**Comment by dwrensha** [comment]
The `Reborrow` trait would look something like this:

```rust
trait Reborrow {
   type Ref<'a>;
   fn reborrow<'a, 'b>(&'b mut Self::Ref<'a>) -> Self::Ref<'b>;
}
```

In particular, it seems to require Generic Associated Types (https://github.com/rust-lang/rust/issues/44265 ), which may explain why it does not exist yet.

**Comment by pfrommerd** [comment]
That makes a lot of sense. Honestly the current system works pretty well, except for the fact that the reborrow() calls tend to clutter code which involves a lot of getters for subslices. An alias .rb() for reborrow() would probably be sufficient, be backwards compatible, and only marginally generate more code. It wouldn't be immediately clear by looking at the code what .rb() means, but realistically if you are building messages you will be doing a lot of reborrowing, so as long as reborrow()/rb() is documented clearly it may be more manageable.

Mutably slicing into buffers safely seems pretty important for any systems language, and the lack of implicit reborrowing for user-defined structures of this kind seems to prevent any real ergonomic wrapping of slices. I guess the best move for now is just to wait.

**Comment by pfrommerd** [comment]
Would it be possible to get rid of reborrow() on the readers? The get methods for the readers should be able to just take &self, which doesn't have the same aliasing problems as with the builders, so we can write

```rust
impl<'s> Reader<'s> {
    fn get_foo(&self) -> Result<Reader<'s>>
}
```
Since we don't have to extend the lifetime of `&mut self` to the returned reader in order to guarantee exclusivity, we should be able to omit reborrow() for this case at least. Such a change should also be backwards compatible, since bar.reborrow().get_foo() would just automatically take a reference to the reborrowed value and have the same return type.

**Comment by dwrensha** [comment]
The main reason that `reborrow()` exists on readers is to allow macros to be written that work on both readers and builders, like this: https://github.com/capnproto/capnproto-rust/blob/267b8b8939fb63b1765741617b98d1029466c917/capnpc/test/test_util.rs#L150-L295

**Comment by jyn514** [comment]
@dwrensha you can still keep the `reborrow` function, it just wouldn't be necessary anymore - *only* the macros would use it.
