### ISSUE TITLE
Detecting disconnect on server and client sides

### ISSUE THREAD

**Issue by crusader-mike** [capnproto/capnproto-rust#283]
Suppose I need to associate some state with a client connection and clean it up if said connection dies (whether it is terminated or deemed "dead" by server due to lack of heartbeat).

For example, let say client connects and somehow gets `Job` interface:
```
interface Job {
    start @0 () -> (cookie :UInt64);
    stop @1 (cookie :UInt64);
}
```

if clients starts a job -- I need server to automatically `stop()` it if **that particular** client connection dies.

Similarly on client side I need to be able to detect broken connection and reconnect (with subsequent `start()` call(s)).

Can this be done with `capnproto`? As I have discovered, it is pretty much impossible with `grpc`...

**Comment by dwrensha** [comment]
How about this?

```capnp
interface JobHandle {
  stop @0 ();
  # Stops the job.

  ping @1 ();
  # Tests that the job is still going and the connection is still alive.
}

interface ClientHandle {
   jobComplete @0 ();
   # Indicates that the job has successfully finished.
}

interface JobStarter {
    start @0 (clientHandle: ClientHandle) -> (jobHandle: JobHandle);
    # Starts a job. The job can be stopped by calling `jobHandle.stop()`,
    # or just by dropping `jobHandle`.
}
```

When the client wants to start a job, they construct a `ClientHandleImpl` object and pass it to `JobStarter.start()`. The server then constructs a `JobHandleImpl` and passes it back to the client. Both `ClientHandleImpl::drop()` and `JobHandleImpl::drop()` can have logic to handle the case when the other side disconnects. The key here is that Cap'n Proto RPC objects are reference-counted across process boundaries, so e.g. if the server passes its only copy of the `JobHandle` reference to the client, and then the client drops that reference, then `JobHandleImpl::drop()` gets called.

To see a simple example of this kind of pattern, take a look at the pubsub example:

https://github.com/capnproto/capnproto-rust/tree/master/capnp-rpc/examples/pubsub

Notice that when you kill one of the clients, the server immediate notices and updates its state.

**Comment by crusader-mike** [comment]
This behaviour looks like exactly what I am looking for...

Few questions:
- is there a heartbeat support? I.e. can I request to RST connection if there were no incoming data for lets say 10 seconds? (I know there are heartbeats on TCP level -- but apparently they are unreliable and it won't help if another transport is used)
- is there a way for client to be immediately notified on disconnect (whether by server or due to lack of heartbeats)? Or it is better to rely on `ClientHandle::drop()` being called and schedule job re-start (which would lead to reconnect)?
- does capnproto ever automatically reconnect?
- in pubsub example:
  - why subscriber [gets removed](https://github.com/capnproto/capnproto-rust/blob/master/capnp-rpc/examples/pubsub/server.rs#L162) if `request.send()` fails? why not rely on auto-unsubscribe in `SubscriptionImpl::drop()`?
  - Does `publisher::Server<::capnp::text::Owned>` means "implementation of Server for Publisher<String>"? So, for each T server has to implement `publisher::Server<::capnp::T::Owned>`? And for client -- create and bootstrap new `rpc_system` (with new connection) for each `T`? (apologies, until ~1h ago I've never heard about capnproto generic)

**Comment by dwrensha** [comment]
> * is there a heartbeat support? I.e. can I request to RST connection if there was no incoming data for lets say 10 seconds? (I know there are heartbeats on TCP level -- but apparently they are unreliable and it won't help if another transport is used)

capnp-rpc does not have anything built in to help with heartbeats. You could call `JobHandle.ping()` every 10 seconds and kill the connection if it fails or times out.

> * is there a way for client to be immediately notified on disconnect on client side (whether by server or due to lack of heartbeats)? Or it is better to rely on `ClientHandle::drop()` being called and schedule job re-start (which would lead to reconnect)?

Adding logic in `ClientHandleImpl::drop()` seems best to me. The RPC system will immediately notice (on the read end) when the connection closes: https://github.com/capnproto/capnproto-rust/blob/70ff536ae66c6008090d2f181c0eb36037c454fd/capnp-rpc/src/twoparty.rs#L152 and that will trigger a disconnect: https://github.com/capnproto/capnproto-rust/blob/70ff536ae66c6008090d2f181c0eb36037c454fd/capnp-rpc/src/rpc.rs#L379 which will cause the object to be dropped.

> * does capnproto ever automatically reconnect?

capnp-rpc does not do any automatic reconnection. I suppose you could maybe pass it `AsyncRead` and `AsyncWrite` objects that have reconnection logic built in to them, but I don't really recommend that. I recommend detecting disconnects as discussed above and triggering your own reconnection logic.

If you want a "Job" to persist across disconnect/reconnect cycles, then you will need to maintain more state, because the `ClientHandle` and `JobHandle` objects will die on each disconnect.

> * in pubsub example:
>   
>   * why subscriber [gets removed](https://github.com/capnproto/capnproto-rust/blob/master/capnp-rpc/examples/pubsub/server.rs#L162) if `request.send()` fails? why not rely on auto-unsubscribe in `SubscriptionImpl::drop()`?

Not all errors are caused by a disconnect. Maybe the subscriber is behaving weirdly, and the publisher want to initiate the disconnect on its end.

>   * Does `publisher::Server<::capnp::text::Owned>` means "implementation of Server for `Publisher<String>`"?

Right, this is a publisher that publishes simple string messages.

>  So, for each T server has to implement `publisher::Server<::capnp::T::Owned>`?

Right, you can plug in any type that implements `capnp::traits::Owned` there. But a `Publisher` must choose only a single type to publish. If you added an additional `impl publisher::Server<::capnp::data::Owned> for PublisherImpl`, for example, then you would need to disambiguate which impl you want here: https://github.com/capnproto/capnproto-rust/blob/70ff536ae66c6008090d2f181c0eb36037c454fd/capnp-rpc/examples/pubsub/server.rs#L117

You would need to replace that `publisher::Client<_>` with `publisher::Client<::capnp::text::Owned>` or `publisher::Client<::capnp::data::Owned>`.

> And for client -- create and bootstrap new `rpc_system` (with new connection) for each `T`? (apologies, until ~1h ago I've never heard about capnproto generic)

The subscriber specifies which type it expects the publisher to be publishing: https://github.com/capnproto/capnproto-rust/blob/70ff536ae66c6008090d2f181c0eb36037c454fd/capnp-rpc/examples/pubsub/client.rs#L60

If the subscriber specifies the wrong type there, then it's possible that it will misinterpret the data.

**Comment by crusader-mike** [comment]
Thank you very much for explanations, @dwrensha. 

> But a Publisher must choose only a single type to publish. If you added an additional impl publisher::Server<::capnp::data::Owned> for PublisherImpl, for example, then you would need to disambiguate which impl you want here:

Does it mean that on given TCP port server can publish either `Publisher<...text>` or `Publisher<...data>`? Is it possible to publish both of them somehow (without starting a second `RpcSystem` on another port)? So that clients can subscribe for `text` or `data` (or other message types) on the same endpoint?

> The subscriber specifies which type it expects the publisher to be publishing:
>...
> If the subscriber specifies the wrong type there, then it's possible that it will misinterpret the data.

What is going to happen if server publishes `Publisher<...text>`, but client connects expecting `Publisher<...data>`? Will it fail or work (but client will be surprised when it tries to interpret received data)? If latter -- can this crash the client somehow?

**Comment by dwrensha** [comment]
> Thank you very much for explanations, @dwrensha.
> 
> > But a Publisher must choose only a single type to publish. If you added an additional impl publisher::Server<::capnp::data::Owned> for PublisherImpl, for example, then you would need to disambiguate which impl you want here:
> 
> Does it mean that on given TCP port server can publish either `Publisher<...text>` or `Publisher<...data>`? Is it possible to publish both of them somehow (without starting a second `RpcSystem` on another port)? So that clients can subscribe for `text` or `data` (or other message types) on the same endpoint?

To have both on a single endpoint you could add a wrapper interface:

```
interface PublisherManager {
   getTextPublisher @0 () -> Publisher(Text);
   getDataPublisher @1 () -> Publisher(Data);
}
```

I don't think there is a way to have a single `PublisherImpl` object handle both versions. You would need a separate object per type. But you would be able to have them work over a single TCP connection.


> 
> > The subscriber specifies which type it expects the publisher to be publishing:
> > ...
> > If the subscriber specifies the wrong type there, then it's possible that it will misinterpret the data.
> 
> What is going to happen if server publishes `Publisher<...text>`, but client connects expecting `Publisher<...data>`? Will it fail or work (but client will be surprised when it tries to interpret received data)? If latter -- can this crash the client somehow?

Usually if a client asks for an interface that a server does not implement, it will receive a "not implemented" error upon calling any methods. However, because type parameters are not included in [`interfaceId`](https://github.com/capnproto/capnproto/blob/ac4e30fd6d6764e2f085bd660e08d19b7360fd81/c%2B%2B/src/capnp/rpc.capnp#L407-L408), in this case there might be no error. The method will succeeded, and the client will get the send message, but will interpret it as the wrong type. A `capnp::text` value can always be interpreted as a `capnp::data` value, so that would work, but in general if there is a mismatch then any traversal of the received message could return a `capnp::Error`. In no case should there be a panic.

**Comment by crusader-mike** [comment]
Beautiful... Reminds me of CORBA, only with DCOM-like reference counting (but without network IO overhead). :-D Thanks a lot for help!

About heartbeats:

> You could call JobHandle.ping() every 10 seconds and kill the connection if it fails or times out.

So, I could add `ping()` method to "root" interface and have a single coroutine that calls it every N seconds (and kill connection on error). How do you kill a connection from client side?

Correspondingly, on server side I need a coroutine that checks `ping()` was called (on every client connection) in last 2*N seconds and kill connection if not.  How to enumerate current connections and get to connection-specific data (timestamp of last `ping()`)? How to kill a connection from server side?

All of this is non-trivial and a bit inefficient (no point generating `ping()` traffic if there was another RPC 1 second ago...) Would be so nice to have this implemented on library level. :) I guess TCP keepalive is probably the most appropriate way to get heartbeats right now...

Quick unrelated question: does this library work with multithreaded executors? (all examples I looked at were using `LocalSet`)

**Comment by dwrensha** [comment]
> Beautiful... Reminds me of CORBA, only with DCOM-like reference counting (but without network IO overhead). :-D Thanks a lot for help!
> 
> About heartbeats:
> 
> > You could call JobHandle.ping() every 10 seconds and kill the connection if it fails or times out.
> 
> So, I could add `ping()` method to "root" interface and have a single coroutine that calls it every N seconds (and kill connection on error). How do you kill a connection from client side?

You could use this:
https://github.com/capnproto/capnproto-rust/blob/70ff536ae66c6008090d2f181c0eb36037c454fd/capnp-rpc/src/lib.rs#L287-L291

> 
> Correspondingly, on server side I need a coroutine that checks `ping()` was called (on every client connection) in last 2*N seconds and kill connection if not. How to enumerate current connections and get to connection-specific data (timestamp of last `ping()`)? How to kill a connection from server side?

You will need to maintain your own data structure containing information about the connections. You can disconnect using `get_disconnector()`. There is not a strong distinction between "client" and "server" in capnp-rpc.


> 
> All of this is non-trivial and a bit inefficient (no point generating `ping()` traffic if there was another RPC 1 second ago...) Would be so nice to have this implemented on library level. :) I guess TCP keepalive is probably the most appropriate way to get heartbeats right now...
> 
> Quick unrelated question: does this library work with multithreaded executors? (all examples I looked at were using `LocalSet`)

All of the RPC system stuff is non-`Send`, so it needs to run on a single thread. You can interop with multi-threaded executors, but unfortunately it tends to be cumbersome. I outlined one idea I had about how to do it here: https://github.com/capnproto/capnproto-rust/issues/271#issuecomment-1146944845

**Comment by dwrensha** [comment]
> Quick unrelated question: does this library work with multithreaded executors? (all examples I looked at were using LocalSet)

If you want to do some cpu-heavy work inside a capnp method call, you can launch that work on a [theadpool](https://docs.rs/futures/0.3.23/futures/executor/struct.ThreadPool.html) and wait asynchronously on the RPC for it to finish.

**Comment by crusader-mike** [comment]
> If you want to do some cpu-heavy work inside a capnp method call ...

No, I was thinking about using `capnproto-rust` in existing application that is running mt executor...

In any case, a lot of thanks for all your help!
