### ISSUE TITLE
Using `CapabilityServerSet` prevents Server objects from being dropped at the appropriate time

### ISSUE THREAD

**Issue by canarysnort01** [capnproto/capnproto-rust#388]
When I use a `CapabilityServerSet` to create clients for Server objects, those Server objects are no longer dropped when the remote connection drops them. These Server objects are kept alive until the `CapabilityServerSet` itself is dropped. 

The behavior I want is for the reference to the Server object to be removed from the `CapabilityServerSet` when it is dropped by the remote connection, so that the Server object may be dropped immediately.

Is it possible to achieve this?

**Comment by dwrensha** [comment]
Good point. Looks like C++ implementation acts as you describe: https://github.com/capnproto/capnproto/blob/851a9e23ea4fb2f1dd0a2d34924407ee612d1da2/c%2B%2B/src/capnp/capability.h#L670-L671

Hm... maybe we could fix that by using `std::rc::Weak` instead of `std::rc::Rc` in the definition of `CapabilityServerSet`: 
https://github.com/capnproto/capnproto-rust/blob/27721b7be92b7d7654a56bae98a6a2ee6b3acf4b/capnp-rpc/src/lib.rs#L325

**Comment by canarysnort01** [comment]
> Hm... maybe we could fix that by using `std::rc::Weak` instead of `std::rc::Rc` in the definition of `CapabilityServerSet`:

I tested this and I think it does what I want. However note that it would change the return types of the accessor methods in `CapabilityServerSet`.

I will create a PR shortly with the changes I tested.

**Comment by dwrensha** [comment]
Ah, I see -- the problem is that we currently return a `&Rc`. That will need to change into an `Rc` (and return `None` if the `Weak` cannot be upgraded).

Maybe for compatibility purposes, `CapabilityServerSet` could have
```
   caps: std::collections::HashMap<usize, Weak<RefCell<C::Dispatch>>>,
   owned_caps: std::collections::HashMap<usize, Rc<RefCell<C::Dispatch>>>,
```

and `owned_caps` only gets populated when the existing `get_local_server()` or `get_local_server_of_resolved()` get called. Then we could add new methods `upgrade_local_server()` and `upgrade_local_server_of_resolved()` that have the new behavior. That way we wouldn't need to make a breaking change.

**Comment by dwrensha** [comment]
Or maybe we make just a separate struct named something like `WeakCapabilitySet` with the new semantics. Then on the next version bump we can remove the existing one.

**Comment by canarysnort01** [comment]
Another downside to this solution is that the invalid entries in the hashmap will never get deleted after the underlying objects get dropped, which could be a source of increasing memory usage for long-running connections with a lot of object creations and deletions.

I doubt removing failed lookups on access would mitigate this since the object almost certainly will still exist when the get_local_* methods are called.

I don't think this would be a concern for my intended usage though.

**Comment by dwrensha** [comment]
I was thinking we would add a `gc(&mut self)` method that would walk through the existing objects and drop the weak pointers that no longer point to anything.

**Comment by canarysnort01** [comment]
> Or maybe we make just a separate struct named something like `WeakCapabilityServerSet` with the new semantics. Then on the next version bump we can remove the existing one.

I think I would prefer to keep the same name as the C++ library concept, unless you think this would be more a more idiomatic name for rust.

**Comment by dwrensha** [comment]
On the version bump we'll rename it back to `CapabilityServerSet` (and maybe keep around a deprecated type alias to `WeakCapabilityServerSet`).

**Comment by canarysnort01** [comment]
Ah, I see. That sounds good to me then.

**Comment by canarysnort01** [comment]
I can take a stab at the changes if you'd like.

**Comment by dwrensha** [comment]
Yes, please go ahead if you're interested.
