### ISSUE TITLE
Compatible versions of capnp C++ implementation?

### ISSUE THREAD

**Issue by crdumoul** [capnproto/capnproto-rust#92]
I have a use case where two processes are communicating with each other using capnproto messages. One side is written in C++ and the other side is written in Rust.

I'd like to understand which versions of capnproto-rust are compatible with which versions of the C++ capnproto library (the reference implementation).

Any help with this would be appreciated.
Thanks.

**Comment by dwrensha** [comment]
capnpc-rust [requires](https://github.com/capnproto/capnproto-rust/blob/a614fa8a094e7c6e1596046a58c2cf1e2d62533a/capnpc/src/lib.rs#L165) version 0.5.2 or higher of the `capnp` schema compiler tool.

Aside from some minor bug fixes, the Cap'n Proto format itself has not undergone any breaking changes since version 0.2 or probably earlier, so there should be no compatibility problems between your C++ and Rust processes.
